Init vars before the backup's fallible operations
Ensure summary_message_lock is initialized before running operations that could
have an exception.

This ensures the intended error message gets displayed as an error box related
to the #482 KeyError.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 129, in do_backup_wrapper
    self.do_backup()
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 149, in do_backup
    if len(self.partitions_to_backup) == 1 and self.partitions_to_backup[0] == "all":
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0
 Moving to mode=Mode.BACKUP on page Page.BACKUP_PROGRESS

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/gtk_ui_manager.py", line 117, in _completed_operation
    callable_fn(succeeded=succeeded, message=message)
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 1036, in completed_backup
    with self.summary_message_lock:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BackupManager' object has no attribute 'summary_message_lock'

Issue #482